/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_model_number_string            20
#define gattdb_serial_number_string           22
#define gattdb_software_revision_string       24
#define gattdb_hardware_revision_string       26
#define gattdb_firmware_revision_string       28
#define gattdb_heart_rate                     29
#define gattdb_heart_rate_measurement         31
#define gattdb_body_sensor_location           34
#define gattdb_respiratory_rate               35
#define gattdb_respiratory_rate_measurement   37
#define gattdb_galvanic_skin_response         39
#define gattdb_galvanic_skin_response_measurement 41
#define gattdb_fatigue                        43
#define gattdb_fatigued_indication            45
#define gattdb_ota                            47
#define gattdb_ota_control                    49


#endif // __GATT_DB_H
